### ISSUE TITLE
For native clients we should use only on JS output

### ISSUE THREAD

**Issue by artemyarulin** [kapteko/kapteko-frontend#6]
Currently we are maintaining two different bundles: `index.ios.js` and `index.android.js`, we should keep only one

**Comment by artemyarulin** [comment]
Due to the https://github.com/facebook/react-native/issues/3984 we cannot change the path for iOS platform.

Well, it's possible if we change the `react-native-xcode.sh`, but that means we have to maintain this by ourselves. Another way to run the packager manually - I wan to avoid it currently. 

Let's change the Android version only and set it to use `index.ios.js` which is not a perfect solution but for now it's OK.

**Comment by localredhead** [comment]
What needs done to have the android version consume `index.ios.js` ?

**Comment by artemyarulin** [comment]
Hm, the only thing that I've changed here was a link in MainActivity https://github.com/kapteko/kapteko-frontend/commit/36cbb838ee143e7cb795a4e60c169ddb358bf96d and it looks like it's enough.

Not sure about gradle files
